# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scripture-slides.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #f0f0f0;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 10px;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLabel{\n"
"    border: 0px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.MainButtons = QtWidgets.QWidget(self.centralwidget)
        self.MainButtons.setGeometry(QtCore.QRect(40, 490, 461, 161))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.MainButtons.setFont(font)
        self.MainButtons.setStyleSheet("#MainButtons{\n"
"    border-radius: 0px;\n"
"}")
        self.MainButtons.setObjectName("MainButtons")
        self.pushButton = QtWidgets.QPushButton(self.MainButtons)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.MainButtons)
        self.label.setGeometry(QtCore.QRect(60, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.MainButtons)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.MainButtons)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.MainButtons)
        self.label_5.setGeometry(QtCore.QRect(60, 90, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.CreatePresentationButton_2 = QtWidgets.QPushButton(self.MainButtons)
        self.CreatePresentationButton_2.setGeometry(QtCore.QRect(100, 90, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(15)
        self.CreatePresentationButton_2.setFont(font)
        self.CreatePresentationButton_2.setStyleSheet("#CreatePresentationButton_2{\n"
"    border: none;\n"
"    color: white;\n"
"    background-color: #2C2C2C;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#CreatePresentationButton_2:hover {\n"
"    border: 2px solid #3498db;\n"
"    color: white;\n"
"    background-color: #3498db; \n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.CreatePresentationButton_2.setObjectName("CreatePresentationButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(570, 30, 601, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.frame.setFont(font)
        self.frame.setStyleSheet("Background-color: #EFEFEF;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fontComboBox = QtWidgets.QFontComboBox(self.frame)
        self.fontComboBox.setGeometry(QtCore.QRect(20, 10, 188, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.IncreaseFontSize = QtWidgets.QPushButton(self.frame)
        self.IncreaseFontSize.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.IncreaseFontSize.setStyleSheet("#IncreaseFontSize{\n"
"    Border: 0px\n"
"}")
        self.IncreaseFontSize.setText("")
        self.IncreaseFontSize.setIcon(icon)
        self.IncreaseFontSize.setIconSize(QtCore.QSize(15, 15))
        self.IncreaseFontSize.setObjectName("IncreaseFontSize")
        self.DecreaseFontSize = QtWidgets.QPushButton(self.frame)
        self.DecreaseFontSize.setGeometry(QtCore.QRect(220, 10, 31, 31))
        self.DecreaseFontSize.setStyleSheet("#DecreaseFontSize{\n"
"    Border: 0px\n"
"}")
        self.DecreaseFontSize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DecreaseFontSize.setIcon(icon1)
        self.DecreaseFontSize.setIconSize(QtCore.QSize(15, 15))
        self.DecreaseFontSize.setObjectName("DecreaseFontSize")
        self.FontSize = QtWidgets.QLabel(self.frame)
        self.FontSize.setGeometry(QtCore.QRect(260, 10, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(16)
        self.FontSize.setFont(font)
        self.FontSize.setStyleSheet("#FontSize{\n"
"    background-color:transparent\n"
"}")
        self.FontSize.setAlignment(QtCore.Qt.AlignCenter)
        self.FontSize.setObjectName("FontSize")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 490, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 490, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.BackgroundFrame = QtWidgets.QFrame(self.centralwidget)
        self.BackgroundFrame.setGeometry(QtCore.QRect(570, 90, 601, 381))
        self.BackgroundFrame.setStyleSheet("#BackgroundFrame{\n"
"Background-color: #D9D9D9;\n"
"border-radius: 10px;\n"
"}")
        self.BackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame.setObjectName("BackgroundFrame")
        self.graphicsView = QtWidgets.QGraphicsView(self.BackgroundFrame)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 581, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.CreatePresentationButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreatePresentationButton.setGeometry(QtCore.QRect(950, 590, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(15)
        self.CreatePresentationButton.setFont(font)
        self.CreatePresentationButton.setStyleSheet("#CreatePresentationButton{\n"
"    border: none;\n"
"    color: white;\n"
"    background-color: #2C2C2C;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#CreatePresentationButton:hover {\n"
"    border: 2px solid #3498db;\n"
"    color: white;\n"
"    background-color: #3498db; \n"
"    border-radius: 20px;\n"
"    transition: background-color 0.3s ease, border 0.3s ease; \n"
"}\n"
"")
        self.CreatePresentationButton.setObjectName("CreatePresentationButton")
        self.BackgroundFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.BackgroundFrame_2.setGeometry(QtCore.QRect(80, 20, 371, 451))
        self.BackgroundFrame_2.setStyleSheet("#BackgroundFrame_2{\n"
"Background-color: #D9D9D9;\n"
"border-radius: 10px;\n"
"}")
        self.BackgroundFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame_2.setObjectName("BackgroundFrame_2")
        self.listWidget = QtWidgets.QListWidget(self.BackgroundFrame_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 351, 431))
        self.listWidget.setStyleSheet("#listWidget{\n"
"    border-radius: 0px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(730, 490, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(790, 490, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.BackgroundFrame_2.raise_()
        self.BackgroundFrame.raise_()
        self.MainButtons.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.pushButton_4.raise_()
        self.CreatePresentationButton.raise_()
        self.pushButton_5.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPresets = QtWidgets.QMenu(self.menuFile)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        font.setPointSize(12)
        self.menuPresets.setFont(font)
        self.menuPresets.setObjectName("menuPresets")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionPresets = QtWidgets.QAction(MainWindow)
        self.actionPresets.setObjectName("actionPresets")
        self.actionImport_Preset = QtWidgets.QAction(MainWindow)
        self.actionImport_Preset.setObjectName("actionImport_Preset")
        self.actionExport_Preset = QtWidgets.QAction(MainWindow)
        self.actionExport_Preset.setObjectName("actionExport_Preset")
        self.actionImport_Preset_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.actionImport_Preset_2.setFont(font)
        self.actionImport_Preset_2.setObjectName("actionImport_Preset_2")
        self.actionExport_Preset_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.actionExport_Preset_2.setFont(font)
        self.actionExport_Preset_2.setObjectName("actionExport_Preset_2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionInformation = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.actionInformation.setFont(font)
        self.actionInformation.setObjectName("actionInformation")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Inter 18pt")
        self.actionVersion.setFont(font)
        self.actionVersion.setObjectName("actionVersion")
        self.menuPresets.addAction(self.actionImport_Preset_2)
        self.menuPresets.addAction(self.actionExport_Preset_2)
        self.menuFile.addAction(self.menuPresets.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionInformation)
        self.menuHelp.addAction(self.actionVersion)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scripture Slides"))
        self.label.setText(_translate("MainWindow", "Slides"))
        self.label_2.setText(_translate("MainWindow", "Background Image"))
        self.CreatePresentationButton_2.setText(_translate("MainWindow", "Slide Verse Repeat"))
        self.fontComboBox.setCurrentText(_translate("MainWindow", "ITC Avant Garde Gothic Pro Book"))
        self.FontSize.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Text"))
        self.CreatePresentationButton.setText(_translate("MainWindow", "Create Presentation"))
        self.label_4.setText(_translate("MainWindow", "Verse"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPresets.setTitle(_translate("MainWindow", "Presets"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPresets.setText(_translate("MainWindow", "Presets"))
        self.actionImport_Preset.setText(_translate("MainWindow", "Import Preset"))
        self.actionExport_Preset.setText(_translate("MainWindow", "Export Preset"))
        self.actionImport_Preset_2.setText(_translate("MainWindow", "Import Preset"))
        self.actionExport_Preset_2.setText(_translate("MainWindow", "Export Preset"))
        self.actionSave.setText(_translate("MainWindow", "Save as..."))
        self.actionInformation.setText(_translate("MainWindow", "Information"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
